org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
minecraft_version=1.21.1
loader_version=21.1.251
java_version=21
mod_version=0.1.0
mod_id=skylasliver_expbook
mod_name=经验之书
mod_license=MIT
maven_group=dev.modmind.skylasliver_expbook
archives_base_name=skylasliver_expbook
neo_version=21.1.251
