modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="skylasliver_expbook"
version="${version}"
displayName="经验之书"
authors="SkylaSliver"
description='''把经验装进书里。书页决定容量，点数按原版公式换算等级。'''

[[mixins]]
config="skylasliver_expbook.mixins.json"

[[dependencies.skylasliver_expbook]]
modId="neoforge"
type="required"
versionRange="[21.1.251,)"
ordering="NONE"
side="BOTH"

[[dependencies.skylasliver_expbook]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
